--DML PARA LLENAR LOS REGISTROS DE LA TABLA TAB_DPTO PRUEBA
-- SELECT * FROM TAB_DPTOS;


-- FUNCIONES DE INSERCION LA TABLA TAB_DPTO ----------------------------------------------------------------------------------------------------------------------------
INSERT INTO tab_dptos VALUES('91','Amazonas');
INSERT INTO tab_dptos VALUES('05','Antioquia');
INSERT INTO tab_dptos VALUES('81','Arauca');
INSERT INTO tab_dptos VALUES('08','Atlántico');
INSERT INTO tab_dptos VALUES('11','Bogotá');
INSERT INTO tab_dptos VALUES('13','Bolivar');
INSERT INTO tab_dptos VALUES('15','Boyacá');
INSERT INTO tab_dptos VALUES('17','Caldas');
INSERT INTO tab_dptos VALUES('18','Caquetá');
INSERT INTO tab_dptos VALUES('85','Casanare');
INSERT INTO tab_dptos VALUES('19','Cauca');
INSERT INTO tab_dptos VALUES('20','Cesar');
INSERT INTO tab_dptos VALUES('27','Chocó');
INSERT INTO tab_dptos VALUES('23','Córdoba');
INSERT INTO tab_dptos VALUES('25','Cundinamarca');
INSERT INTO tab_dptos VALUES('94','Guanía');
INSERT INTO tab_dptos VALUES('95','Guaviare');
INSERT INTO tab_dptos VALUES('41','Huila');
INSERT INTO tab_dptos VALUES('44','La Guajira');
INSERT INTO tab_dptos VALUES('47','Magdalena');
INSERT INTO tab_dptos VALUES('50','Meta');
INSERT INTO tab_dptos VALUES('52','Nariño');
INSERT INTO tab_dptos VALUES('54','Norte de Santander');
INSERT INTO tab_dptos VALUES('86','Putumayo');
INSERT INTO tab_dptos VALUES('63','Quindío');
INSERT INTO tab_dptos VALUES('66','Risaralda');
INSERT INTO tab_dptos VALUES('68','Santander');
INSERT INTO tab_dptos VALUES('70','Sucre');
INSERT INTO tab_dptos VALUES('73','Tolima');
INSERT INTO tab_dptos VALUES('76','Valle del Cauca');
INSERT INTO tab_dptos VALUES('88','Archipiélago de San Andrés');
INSERT INTO tab_dptos VALUES('97','Vaupés');
INSERT INTO tab_dptos VALUES('99','Vichada');